FROM oven/bun:1

WORKDIR /user/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./apps/http-backend ./apps/http-backend
COPY ./bun.lock  ./bun.lock  
COPY ./package.json  ./package.json  
COPY ./turbo.json ./turbo.json

RUN bun install 
RUN bun run db:generate 

EXPOSE 3001

CMD [ "bun", "run", "start:http-backend" ]



