FROM oven/bun:1

WORKDIR /user/src/app

ARG DATABASE_URL=postgresql://postgres:mysecretpassword@localhost:5432/postgres

COPY ./packages ./packages
COPY ./apps/web ./apps/web 
COPY ./bun.lock  ./bun.lock  
COPY ./package.json  ./package.json  
COPY ./turbo.json ./turbo.json

RUN bun install 
RUN DATABASE_URL=${DATABASE_URL} bun run db:generate 
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000 

CMD [ "bun", "run", "start:web" ]



