name: "Deploy the http backend"
on:
  push:
    branches: ["main"]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: "Docker login"
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.http
          build-args: |
            DATABASE_URL=${{secrets.DATABASE_URL}}
          push: true
          tags: whowasthat/todo-app-http:${{github.sha}}

      - name: "Install SSH key"
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "Deploy to VM"
        run: ssh -o StrictHostKeyChecking=no adarsh@${{secrets.SERVER_IP}} "docker stop http-backend || true && docker run --name http-backend -d -p 3001:3001 whowasthat/todo-app-http:${{github.sha}}"
